### ISSUE TITLE
Small issue in Vessel_sim_GPU

### ISSUE THREAD

**Issue by yiqunma** [jewhiteh/HepaticVesselGeneration#1]
Thank you for this easy-to-use tool and instructions!

In the GPU version (CPU version is ok) several function declarations are inconsistent with their function definitions. The following function declarations in `phantom.h` are missing the `float outResolutionScaleFactor` parameter:

`build_tree`
`polyInterp`
`polyInterpWithControlPoints`
`optimizeAngles`

I could clear the errors by simply adding the `float outResolutionScaleFactor` to the function declarations in `phantom.h`. 
![image](https://github.com/jewhiteh/HepaticVesselGeneration/assets/40863480/5b891568-6715-4a12-b02d-d1351a4c03d0)
![image](https://github.com/jewhiteh/HepaticVesselGeneration/assets/40863480/f0c460e0-e87f-4c17-bc92-953b117cd28a)

Lastly, a minor typo in the README.pdf: "readTree.mat" should be "readTree.m" 😃

**Comment by jewhiteh** [comment]
Thank you @yiqunma, I have included all of your comments. Sorry for the slow response! Please let me know if you find anything else. All the best!

**Comment by jewhiteh** [comment]
Thank you @yiqunma, I have included all of your comments. Sorry for the slow response! Please let me know if you find anything else. All the best!
